name: "aictl-query"
author: "Akira Masuda (go-zen-chu)"
description: "Handy tool for asking questions and reviews to AI"
inputs:
  # required
  query:
    description: "Query to ask AI. You can ask anything"
    required: true
  # optional
  language:
    description: "Which language you want to get response (default is English)"
    default: "English"
  output:
    description: "Output format (default is JSON)"
    default: "text"
  text-files:
    description: "An array of text files added to query seperated with comma (e.g. file1.go,file2.txt)"
  verbose:
    description: "Verbose log"
    default: "false"
runs:
  using: "docker"
  image: "docker://amasuda/aictl:latest"
  args:
    - --verbose=${{ inputs.verbose }}
    - query
    - --language=${{ inputs.language }}
    - --output=${{ inputs.output }}
    - --text-files=${{ inputs.text-files }}
    - ${{ inputs.query }}
branding:
  icon: "cloud"
  color: "blue"
