name: tag-release
on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    name: Release binary with goreleaser
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Install Dev tools
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: InstallDevTools
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
